"""`allcrew-channel demo init|up` — a self-contained Django stand for browsing exports.

`init` scaffolds a minimal project WIRED FOR THE PLUGIN'S LAYOUT: `TEMPLATES.DIRS` and
`STATICFILES_DIRS` point at the project-root `templates/` and `static/` the export.zip
unpacks into. Stock `startproject` settings only see app-level dirs (APP_DIRS), which is
the classic "apply said 297 files written but the page shows the old import" trap. It
also creates `.venv` with Django installed so `check`/`serve` never hit the CLI's bare
interpreter. `up` chains init → apply → serve: zip in, browsable stand out.

Scaffolded files carry a MARKER comment; `init` only rewrites files it generated itself,
so an adopted (hand-made) project is never touched beyond the venv.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from .pyenv import has_django, project_python, venv_python

MARKER = "generated by allcrew-channel demo init"

_MANAGE_PY = f'''#!/usr/bin/env python3
# {MARKER}
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "demo_site.settings")
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
'''

_SETTINGS_PY = f'''# {MARKER} — a dev-only stand for browsing the plugin's exports; never deploy this.
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "allcrew-channel-demo-stand"
DEBUG = True
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = ["django.contrib.staticfiles"]
MIDDLEWARE = []
ROOT_URLCONF = "demo_site.urls"

# The plugin's export.zip unpacks templates/ and static/ at the PROJECT root — wire the
# loaders there (stock startproject settings only see app-level dirs via APP_DIRS).
TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": False,
        "OPTIONS": {{"context_processors": ["django.template.context_processors.request"]}},
    }}
]
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

LANGUAGE_CODE = "en"
USE_I18N = True
LOCALE_PATHS = [BASE_DIR / "locale"]
USE_TZ = True
DATABASES = {{}}
'''

_URLS_PY = f'''# {MARKER}
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("page/<str:name>", views.page, name="page"),
]
'''

_VIEWS_PY = f'''# {MARKER} — browse the exported pages; navMap feeds the {{{{ navMap.nav_… }}}}
# links the plugin emits for Figma NAVIGATE reactions.
import re

from django.conf import settings
from django.http import Http404
from django.shortcuts import render


def _page_templates():
    pages_dir = settings.BASE_DIR / "templates" / "pages"
    if not pages_dir.is_dir():
        return []
    return sorted(path.name for path in pages_dir.glob("*.html"))


def _nav_map():
    # pages/one-main--4110-62538.html → nav_4110_62538: the template filename ends with the
    # source frame's id slug (the plugin's navMapKey convention).
    nav = {{}}
    for name in _page_templates():
        stem = name[: -len(".html")]
        if "--" not in stem:
            continue
        id_slug = stem.rsplit("--", 1)[1]
        key = "nav_" + re.sub(r"[^A-Za-z0-9]+", "_", id_slug).strip("_")
        nav[key] = f"/page/{{name}}"
    return nav


def index(request):
    return render(request, "demo/index.html", {{"pages": _page_templates()}})


def page(request, name):
    if name not in _page_templates():
        raise Http404(f"no exported page template named {{name}}")
    return render(request, f"pages/{{name}}", {{"navMap": _nav_map()}})
'''

_INDEX_HTML = f'''{{# {MARKER} #}}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>allcrew-channel demo stand</title>
  <style>body {{ font: 16px/1.5 system-ui; margin: 40px auto; max-width: 640px; padding: 0 16px }} a {{ color: #fb5b0a }}</style>
</head>
<body>
  <h1>Exported pages</h1>
  {{% if pages %}}
  <ul>{{% for name in pages %}}<li><a href="/page/{{{{ name }}}}">{{{{ name }}}}</a></li>{{% endfor %}}</ul>
  {{% else %}}
  <p>No exported pages yet — run <code>allcrew-channel apply export.zip --app .</code></p>
  {{% endif %}}
</body>
</html>
'''

_REQUIREMENTS = "django>=6,<7\n"

_SCAFFOLD = {
    "manage.py": _MANAGE_PY,
    "demo_site/__init__.py": f"# {MARKER}\n",
    "demo_site/settings.py": _SETTINGS_PY,
    "demo_site/urls.py": _URLS_PY,
    "demo_site/views.py": _VIEWS_PY,
    "templates/demo/index.html": _INDEX_HTML,
}


def _write_scaffold(app_dir: Path) -> list[str]:
    written = []
    for relative, content in _SCAFFOLD.items():
        target = app_dir / relative
        if target.exists() and MARKER not in target.read_text(errors="replace"):
            continue  # hand-made file — adopt, never overwrite
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        written.append(relative)
    for directory in ("templates/pages", "static"):
        (app_dir / directory).mkdir(parents=True, exist_ok=True)
    if not (app_dir / "requirements.txt").exists():
        (app_dir / "requirements.txt").write_text(_REQUIREMENTS)
        written.append("requirements.txt")
    return written


def _ensure_venv(app_dir: Path) -> int:
    if venv_python(app_dir) is None:
        print(f"[allcrew-channel demo] creating venv at {app_dir / '.venv'}")
        created = subprocess.run([sys.executable, "-m", "venv", str(app_dir / ".venv")])
        if created.returncode != 0:
            return created.returncode
    python = project_python(app_dir)
    if not has_django(python):
        print("[allcrew-channel demo] installing requirements (Django) into the venv")
        installed = subprocess.run(
            [python, "-m", "pip", "install", "--quiet", "-r", str(app_dir / "requirements.txt")]
        )
        if installed.returncode != 0:
            return installed.returncode
    return 0


def run_init(args) -> int:
    app_dir = Path(args.app).resolve()
    app_dir.mkdir(parents=True, exist_ok=True)

    if (app_dir / "manage.py").exists() and MARKER not in (app_dir / "manage.py").read_text(errors="replace"):
        print(f"[allcrew-channel demo] existing Django project at {app_dir} — leaving its files alone")
        print("  (root-level templates/static need TEMPLATES.DIRS/STATICFILES_DIRS wiring there)")
    else:
        written = _write_scaffold(app_dir)
        if written:
            print(f"[allcrew-channel demo] scaffolded {len(written)} file(s) under {app_dir}:")
            for relative in written:
                print(f"  {relative}")
        else:
            print(f"[allcrew-channel demo] stand at {app_dir} is up to date")

    if not args.no_venv:
        venv_status = _ensure_venv(app_dir)
        if venv_status != 0:
            return venv_status
        print(f"[allcrew-channel demo] python: {project_python(app_dir)}")

    print(f"[allcrew-channel demo] next: allcrew-channel apply export.zip --app {app_dir} && allcrew-channel serve --app {app_dir}")
    return 0


_ASSUME_CSS_COMMENT = "Bootstrap CSS is expected from the project"
_ASSUME_JS_COMMENT = "Bootstrap JS (bundle) is expected from the project"
# Mirrors the plugin's emitBaseHtml: Bootstrap goes into a CSS cascade layer so the export's
# un-layered custom CSS (the pixel-exact Figma look) wins every property conflict regardless of
# specificity (.btn:hover / .btn-group corner-zeroing can't override it). Utilities stay !important.
_VENDOR_CSS_LINK = "  <style>@import url(\"{% static 'vendor/bootstrap/bootstrap.min.css' %}\") layer(bootstrap);</style>"
_VENDOR_JS_LINK = "  <script src=\"{% static 'vendor/bootstrap/bootstrap.bundle.min.js' %}\" defer></script>"


def vendored_bootstrap_present(app_dir: Path) -> bool:
    vendor_dir = app_dir / "static" / "vendor" / "bootstrap"
    return (vendor_dir / "bootstrap.min.css").exists() and (vendor_dir / "bootstrap.bundle.min.js").exists()


def relink_assume_to_vendored(app_dir: Path) -> bool:
    """Rewrites base.html's 'assume'-mode framework blocks (comment-only) to link the vendored
    Bootstrap files. `apply` regenerates base.html from the export every run, so an assume-mode
    export silently drops the Bootstrap <link> — and the whole utility-class base layout
    (d-flex/d-grid) dies while only the @media raw-CSS survives. Callers relink after apply so
    the stand keeps working. Returns whether base.html changed. Idempotent."""
    base_html = app_dir / "templates" / "base.html"
    if not base_html.exists():
        return False
    text = base_html.read_text()
    if _ASSUME_CSS_COMMENT not in text:
        return False
    lines = [
        _VENDOR_CSS_LINK if _ASSUME_CSS_COMMENT in line else _VENDOR_JS_LINK if _ASSUME_JS_COMMENT in line else line
        for line in text.splitlines()
    ]
    base_html.write_text("\n".join(lines) + ("\n" if text.endswith("\n") else ""))
    return True


def _ensure_bootstrap(app_dir: Path, url_base: str) -> int:
    """The export's utility classes (d-grid, align-items-*, …) are dead weight without
    Bootstrap's CSS. Make the stand self-sufficient: relink 'assume' blocks to the vendored
    files and download Bootstrap once into static/vendor/bootstrap/."""
    base_html = app_dir / "templates" / "base.html"
    if not base_html.exists():
        return 0
    if relink_assume_to_vendored(app_dir):
        print("[allcrew-channel demo] base.html: framework blocks relinked to the vendored Bootstrap")
    elif "vendor/bootstrap/" not in base_html.read_text():
        return 0  # project manages Bootstrap itself (not assume, not vendored) — leave it

    if vendored_bootstrap_present(app_dir):
        return 0
    from . import vendor

    print("[allcrew-channel demo] fetching Bootstrap into static/vendor/bootstrap/")
    return vendor.run(argparse.Namespace(app=str(app_dir), version="5.3", url_base=url_base))


def run_up(args) -> int:
    app_dir = Path(args.app).resolve()
    init_status = run_init(argparse.Namespace(app=args.app, no_venv=args.no_venv))
    if init_status != 0:
        return init_status

    from . import apply as apply_module

    apply_status = apply_module.run(argparse.Namespace(zip=args.zip, app=str(app_dir), dry_run=False))
    if apply_status != 0:
        return apply_status

    bootstrap_status = _ensure_bootstrap(app_dir, args.url_base)
    if bootstrap_status != 0:
        return bootstrap_status

    from . import serve as serve_module

    serve_status = serve_module.run_serve(
        argparse.Namespace(app=str(app_dir), port=args.port, host="127.0.0.1", foreground=False)
    )
    if serve_status != 0:
        return serve_status

    print(f"\n[allcrew-channel demo] stand ready → http://127.0.0.1:{args.port}/")
    return 0
